### ISSUE TITLE
Update user guide to virocon version 2

### ISSUE THREAD

**Issue by ahaselsteiner** [virocon-organization/virocon#106]
With version 2 many things have been changed: The software architecture has been revised and code is not backwards compatible with virocon version 1.X.

- [x] Create concept for new user guide
- [x] Provide examples and also add these examples as scripts in the "examples" folder (use the same examples that @kawindme used in his WESC presentation and make the presentation publicly avialable?)
- [x] Cheat sheet for dictionaries in user guide of virocon

**Comment by kawindme** [comment]
Cheat sheet is created in  #107.

**Comment by ahaselsteiner** [comment]
Done. The new user guide is available at: https://virocon.readthedocs.io/en/latest/user_guide.html
