### ISSUE TITLE
WidthOfIntervalSlicer references 

### ISSUE THREAD

**Issue by lenastroeer** [virocon-organization/virocon#137]
**I'm submitting a ...**
  -  bug report

## Expected behavior
When defining an interval like this: 
width_slicer = WidthOfIntervalSlicer(width=2, reference="right", min_n_points=10) 
I would expect, that the reference of the interval is right. Actually, the reference of the interval is in the center. 
As I understand it, right now the references in WidthOfIntervalSlicer do not output the indicated reference: 
- right = center
- center = left
- left = right

**Screenshot**

<img width="1068" alt="Bildschirmfoto 2021-09-15 um 17 51 11" src="https://user-images.githubusercontent.com/57865209/133469622-4ff091b0-2a7f-4ad9-8ab9-39d11ec74532.png">
<img width="1068" alt="Bildschirmfoto 2021-09-15 um 17 51 21" src="https://user-images.githubusercontent.com/57865209/133469628-d80625b5-440f-4b2b-9fcb-0db4119e2cc3.png">
<img width="1068" alt="Bildschirmfoto 2021-09-15 um 17 51 30" src="https://user-images.githubusercontent.com/57865209/133469632-b9525e84-e4c8-4a32-aa2b-9599a5eeda40.png">

**Comment by kawindme** [comment]
This seems to be a bug in the computation of the intervals boundaries. This might also be the case for the NumberOfIntervalsSlicer. 
Next steps would be:
1. create test cases that fail while this bug is unfixed
    - preferably use the dummy data already defined in test_intervals.py
    - manually compute the expected results and create test cases with these
2. fix the bug in intervals.py
    - move the computation of the boundaries to the if-else clauses that differentiate between "left", "right", "center"
    - make sure the previously defined test cases now pass

**Comment by ahaselsteiner** [comment]
@lenastroeer I think this issue was fully addressed in PR #139? If, yes please feel free to close this issue.

**Comment by lenastroeer** [comment]
@ahaselsteiner yes, that's true, thanks!  I'll close this issue!
