### ISSUE TITLE
Change naming of 'NumberOfIntervalsSlicer'

### ISSUE THREAD

**Issue by lenastroeer** [virocon-organization/virocon#138]
**I'm submitting a ...**
  - code improvement request

## Issue:
We realized, that the naming of the functions in IntevalSlicer is not consistent:

**Screenshot**
<img width="700" alt="Bildschirmfoto 2021-09-21 um 16 07 53" src="https://user-images.githubusercontent.com/57865209/134186549-39663db6-e368-4f11-b32e-3daff8797f62.png">

## Improvement:
The 's' in 'NumberOfIntervalsSlicer' will be deleted in order to avoid typing errors when using virocon. We will add a deprecation warning when importing the IntervalSlicer.

**Comment by kawindme** [comment]
After searching for a while I found this: https://stackoverflow.com/a/52087847 solution to deprecate a class. 
Did we consider to simply rename the Slicer but keep the current name as an alias?
We would then replace all occurrences in the docs with the new name, but allow to use the current name as well.

**Comment by ahaselsteiner** [comment]
Looking at this issue again after some time I think we should keep things as is. 

`NumberOfIntervals` is grammatically right such that there is a good reason for the 's' here.

@kawindme unless you disagree, I'll close the issue in a couple of days.
