### ISSUE TITLE
Addition of probability distribution (Von Mises distribution)

### ISSUE THREAD

**Issue by frp09** [virocon-organization/virocon#156]
**I'm submitting a ...**
  - [ ] code improvement request

Dear Virocon team, 

Thank you for the very useful tool you have developed. I am new to pull requests and issues (I'm a first timer actually) so hopefully I'm doing this as intended. Anyway, I have added the Von Mises distribution to the distributions.py file. I used this distribution to model wind-wave misalignment, which is a relevant environmental parameter for offshore wind turbines. 

Also I think there may be a bug in the normal distribution definition, and I corrected it editing line 864. 

I submitted a pull request for you to consider merging into the code. https://github.com/frp09/virocon/compare/master...frp09-vmd

Best, 

Francesco

**Comment by kawindme** [comment]
Hi Francesco, 

thanks for your work, glad you like virocon so far. 
The PR you created is intern to your own fork of virocon, i.e. you created a PR from your branch frp09-vmd to your own master branch (this is not the same as virocon/master). 
We would like to accept your PR though, so I created this PR #157. 
I would suggest we continue any discussions there.

Best, 
Kai

**Comment by kawindme** [comment]
I realize now, that me creating the PR might not emphasize enough that this is your contribution. Feel free to create another PR from your frp09-vmd branch to virocon-organizations master.

**Comment by kawindme** [comment]
The new distribution is available now in version 2.1.0 published on PyPI (not yet on conda). I will leave this Issue open for now in case you want to continue any discussions started in #157. 
Nice work! :+1:
