### ISSUE TITLE
Missing .coveragerc?

### ISSUE THREAD

**Issue by kawindme** [virocon-organization/virocon#159]
The pyproject.toml file sets the options for pytest. It expects a .coveragerc file which does not exist in the master branch. Is the .coveragerc file missing or should we simply delete that config option?

**Comment by ahaselsteiner** [comment]
Are there any options for pytest that you would like to specify? If not, let's delete the config file if that is an option 🧹

**Comment by ahaselsteiner** [comment]
Is something not working because `pyproject.toml` expects a `.coveragerc` file @kawindme ?

If everything is working fine I'd close this issue.
