### ISSUE TITLE
Allow users to fix some values of the dependence functions before fitting

### ISSUE THREAD

**Issue by ahaselsteiner** [virocon-organization/virocon#32]
DNVGL's new standard DNVGL-ST-0119 on floating wind turbine structures proposes a new model structure for the relationship between Hs and Tp. The fist coefficient of the power and expoential function is fixed. 

To allow users to use this DNVGL model, users should be able to fix some values of the dependence function such that only two instead of three coeffcients are fit.

This is the model structure that DNVGL proposes:
Allow users to fix some values of the dependence function such that only two instead of three coeffcients are fit:

![image](https://user-images.githubusercontent.com/11452055/48002428-cf15c380-e10b-11e8-9d3b-803eff97eb2e.png)

**Comment by BeyondLee518** [comment]
Hello Andreas，
 I was running Fit_distribution_similar_to_docs. Py, but this issue occurred 'Traceback (most recent call Last):
File "fit_similtion_to_docs.py ", line 12, in &lt;Module&gt;
Read_ecbenchmark_dataset (' datasets / 1 year_dataset_a. TXT)
File "D:\Python3\lib\site-packages\viroconcom\read_write.py", line 38, in read_ecbenchmark_dataset
With open(path, newline= ") as CSV_file:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/ 1year_dataset_a.txt ', 
what should you do?
Thanks very much!

**Comment by ahaselsteiner** [comment]
Hi Beyond,

 

it seems that viroconcom does not find the file that holds that datasets in your case.

 

I think that could have two reasons:

·         Do you have the dataset in your repository? Get the newest version of viroconcom using “git pull” and manually check that the file is there

·         Possibly you are calling the python file from a different place than the viroconcom home repository such that from wherever you call the python file there is not the “datasets” folder. You must call “fit_distribution_similar_to_docs.py” from the viroconcom home repository (see attached screenshot).

 

Cheers,

Andreas

 

Von: Beyond <notifications@github.com> 
Gesendet: Friday, July 31, 2020 4:55 PM
An: virocon-organization/viroconcom <viroconcom@noreply.github.com>
Cc: Andreas Haselsteiner <a.haselsteiner@uni-bremen.de>; Author <author@noreply.github.com>
Betreff: Re: [virocon-organization/viroconcom] Allow users to fix some values of the dependence functions before fitting (#32)

 

Hello Andreas，
I was running Fit_distribution_similar_to_docs. Py, but this issue occurred 'Traceback (most recent call Last):
File "fit_similtion_to_docs.py ", line 12, in <Module>
Read_ecbenchmark_dataset (' datasets / 1 year_dataset_a. TXT)
File "D:\Python3\lib\site-packages\viroconcom\read_write.py", line 38, in read_ecbenchmark_dataset
With open(path, newline= ") as CSV_file:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/ 1year_dataset_a.txt ',
what should you do?
Thanks very much!

**Comment by BeyondLee518** [comment]
Ok, I've solved that.Thank you for Andreas.But I still want to ask you, I now have a PDF of wave height and spectrum peak period, and I also have a PDF of wind speed, but they are independent, how to combine them?Because it feels like they have no temporal correlation

**Comment by BeyondLee518** [comment]
Another problem is that I have obtained the environmental contour  of wave height and spectral peak period, but how to extract the data of the environmental contour  and the corresponding parameters?

**Comment by ahaselsteiner** [comment]
@BeyondLee518 about your first question on defining the dependence structure: Have a look at this chapter of the contribution guide (and let me know in case you are still having the problem): https://virocon-organization.github.io/viroconcom/fitting.html

On the second problem: To access the contour's coordinates, print the contour's coordinate attribute. Have a look at this example: https://github.com/virocon-organization/viroconcom/blob/master/examples/compare_contour_methods.py
You could write:
print(contour.coordinates[0])
and
print(contour.coordinates[1])

To access the joint distribution's parameter values, print the univariate distributions.
The Fit object has a MultivariateDistribution attribute: fit.mul_var_dist
The MultivariateDistribution contains a list of univariate distributions that you can access as fit.mul_var_dist.distributions .
If you print these individual distributions, you see the parameter values.
Have a look at this example: https://github.com/virocon-organization/viroconcom/blob/master/examples/fit_distribution_similar_to_docs.py#L30
In this example. you could add at line 35:
print(fitted_hs_dist)
print(fitted_tz_dist)

Alternatively, you can use the plot_dependence_function() method, which will output you the dependence function as a label.

**Comment by ahaselsteiner** [comment]
With the release of virocon 2.0 this is possible. In this big rewrite we now allow users to write custom dependence functions. 

I think we should provide the model described in DNVGL-ST-0119 as a predefined model, or do you see arguments against providing this standard model @kawindme?

**Comment by kawindme** [comment]
I am not sure how easy it is to include this model. If i understand it correctly, this model does not provide equations for the parameters of a lognormal distribution as it is currently implemented in virocon, but rather the mean and standard deviation. I suspect we would have to provide a differently parametrized lognormal distribution class, e.g. as we did with the LogNormalNormFitDistribution. As this would then already be the second case where we would need a lognormal distributions parametrized by its mean and std, we might think about including such a distribution in virocon.

**Comment by ahaselsteiner** [comment]
@kawindme The model uses dependence functions for the usual parameters, sigma and mu.

![image](https://user-images.githubusercontent.com/11452055/119958232-236f4000-bfa3-11eb-9ea6-14b3a9df8d4f.png)

mu is not the mean of the distribution, but the mean of ln(distribution). These are the typical log-normal distribution parameters that we also implemented in virocon.

**Comment by kawindme** [comment]
If that is the case, then this should be easy to include.

**Comment by kawindme** [comment]
It is easy to implement this model now with virocon>=2.0.0.
But it seems to me, that there is currently no demand to include this model in our predefined module.
Thus I will close this issue. 
If you still think this model should be included, feel free to reopen or create a new issue.
