### ISSUE TITLE
Move minimum number of data points per fitting intervals option 

### ISSUE THREAD

**Issue by kawindme** [virocon-organization/virocon#66]
**I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] code improvement request

## Expected behavior
**How should it work (with the bug fixed or the feature implemented)?**
Move option to specify minimum number of data points per interval to the conditioning variable definition.

**Screenshot**

## Actual behavior
**How does it currently work (with the bug causing problems or without the feature)?**
At the moment this option has to be specified at the definition of the conditional variable.

see e.g. https://github.com/ahaselsteiner/2020-paper-omae-hierarchical-models/blob/master/compute_contours_datasets_abc.py#L20

**Comment by ahaselsteiner** [comment]
The complete architecture of the fitting functionality has changed in virocon. This issue has been solved.
