### ISSUE TITLE
Allow parameter estimation via mean and std

### ISSUE THREAD

**Issue by kawindme** [virocon-organization/virocon#85]
**I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] code improvement request

## Expected behavior

In https://doi.org/10.5194/wes-4-325-2019 a log-normal distribution is fitted, by first computing the mean and standard deviation for each bin. Then polynomials are fitted to mean and std. The parameters of the log-normal are then derived using https://en.wikipedia.org/wiki/Log-normal_distribution#Estimation_of_parameters . 
This behaviour is recommended in IEC 61400-1. 

This should work at least for the log-normal distribution, but could also be extended to other distributions, for which the parameters can be estimated similarly.

**Comment by ahaselsteiner** [comment]
@kawindme is this functionality available in VC2? Should we close this issue?

**Comment by kawindme** [comment]
In principle this is possible, but it requires sub-classing the LogNormalDistribution. At the moment this is implemented in distributions.LogNormalNormFitDistribution. As we want to remove that class though, we will lose this functionality.

**Comment by ahaselsteiner** [comment]
What do you think about creating a predefined model for this joint distribution? And moving distributions.LogNormalNormFitDistribution into the respective function in predefined.py (we wanted to move distributions.LogNormalNormFitDistribution anyway)?

**Comment by kawindme** [comment]
This sounds like a good idea! The only drawback might be, that the predefined module grows quite fast now. But this could be handled by transforming the module to a package.

**Comment by ahaselsteiner** [comment]
I am closing this issue as I don't think we will follow up on it.
